### ISSUE TITLE
Receiving error when calling GetUploadTicketAsync: String was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by sebastians86** [mfilippov/vimeo-dot-net#126]
First of all, thanks for making this great c# wrapper for the Vimeo API. It makes my life a whole lot easier!

Just today, our clients started receiving errors when trying to upload videos. After digging into our code to troubleshoot the issue, I discovered that the error is being thrown when we call GetUploadTicketAsync. This is how we call it:

```
// generate new upload ticket
VimeoClient vimeoClient = new VimeoClient(ApiOptions.Token);
UploadTicket ticket = await vimeoClient.GetUploadTicketAsync();
```

Nothing has changed in our code in a while and the exception message is as follows:

```
   at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at VimeoDotNet.VimeoClient.UpdateRateLimit(IApiResponse response) in C:\projects\vimeo-dot-net\src\VimeoDotNet\VimeoClient_RateLimit.cs:line 48
   at VimeoDotNet.VimeoClient.<GetUploadTicketAsync>d__73.MoveNext() in C:\projects\vimeo-dot-net\src\VimeoDotNet\VimeoClient_Upload.cs:line 24
```

It looks like the "X-RateLimit-Reset" header is not read properly in the VimeoClient_RateLimit.cs file.

**Comment by sebastians86** [comment]
I downloaded the source code of the project and the X-RateLimit-Reset header actually returns an integer value of the unix timestamp (see [https://developer.vimeo.com/guidelines/rate-limiting](url)). I replaced the following line of code in VimeoClient_RateLimit.cs on line 45 as follows:

Changed:
```
RateLimitReset = DateTime.ParseExact(response.Headers.GetValues("X-RateLimit-Reset").First(),
                    "yyyy-MM-ddTHH:mm:sszzz", CultureInfo.InvariantCulture, DateTimeStyles.AdjustToUniversal);
```

To:
```
var unixTime = long.Parse(response.Headers.GetValues("X-RateLimit-Reset").First());
var epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
RateLimitReset = epoch.AddSeconds(unixTime);
```

It seems to work.

**Comment by sebastians86** [comment]
This is odd, the "X-RateLimit-Reset" header is now returning the datetime value it used to before, not an integer. The documentation page I referenced also changed. Not sure what happened on Vimeo's end, I couldn't find anything.
